# Generated by Django 5.2.4 on 2025-08-11 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0008_categoria_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipo',
            name='slug',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
